[package]
name = "rapace"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
description = "Async RPC over functions or sockets"

[dependencies]
facet = { git = "https://github.com/facet-rs/facet" }
facet-postcard = { git = "https://github.com/facet-rs/facet" }
tokio = { version = "1", features = ["sync", "io-util", "rt", "rt-multi-thread", "macros", "time"] }
paste = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
