[package]
name = "mod-html-diff-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
facet = { version = "0.32.2" }
rapace = { git = "https://github.com/bearcove/rapace" }
dodeca-protocol = { path = "../../crates/dodeca-protocol" }