[package]
name = "dodeca-cell-runtime"
version = "0.6.1"
edition = "2024"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
cell-lifecycle-proto = { path = "../../cells/cell-lifecycle-proto" }
roam.workspace = true
roam-shm.workspace = true
roam-tracing.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
