[package]
name = "dodeca-cell-runtime"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
rapace.workspace = true
rapace-cell.workspace = true
rapace-tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["registry"] }
tokio = { version = "1", features = ["full"] }
color-eyre = "0.6"
tracing = "0.1"
libc = "0.2"
dodeca-debug = { path = "../dodeca-debug" }
