[package]
name = "integration-tests"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
publish = false

[[bin]]
name = "integration-tests"
path = "src/main.rs"

[dependencies]

# For Unix socket FD passing
async-send-fd = { version = "1.2", features = ["tokio"] }

# Colorful output
owo-colors = "4"
regex = { workspace = true } #unified
tempfile = { workspace = true } #unified
ureq = { version = "3", default-features = false }
tokio = { workspace = true, features = ["macros", "process", "rt", "rt-multi-thread", "sync", "time"] } #unified
tracing = { workspace = true } #unified
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Death-watch for child processes
ur-taking-me-with-you.workspace = true
