[package]
name = "cell-config-proto"
version = "0.6.1"
edition = "2024"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
dodeca-config = { path = "../../crates/dodeca-config" }
facet.workspace = true
roam.workspace = true
