[package]
name = "mod-linkcheck-proto"
version = "0.1.0"
edition = "2024"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
facet = { version = "0.32.2" }
rapace.workspace = true
