[package]
name = "dodeca-plugin-runtime"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
rapace = { git = "https://github.com/bearcove/rapace" }
rapace-plugin = { git = "https://github.com/bearcove/rapace" }
rapace-tracing = { git = "https://github.com/bearcove/rapace" }
tracing-subscriber = { version = "0.3", features = ["registry"] }
tokio = { version = "1", features = ["full"] }
